[package]
name = "fin"
version = "0.1.0"
authors = ["silvio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode_reader = "1.0.1"
clap = "2.33"
chrono = "0.4"
rust_decimal = "1.8.1"
